# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
  config.vm.define "apache" do |apache|
    apache.vm.box = "ubuntu/bionic64"
    apache.vm.network "private_network", ip: "192.168.30.10"
    apache.vm.network "public_network", ip: "192.168.30.40"
    apache.vm.network "forwarded_port", guest: 80, host: 80
    apache.vm.provision "shell", inline: <<-SHELL
      echo "apache" > /etc/hostname
      hostname -b apache
      echo "192.168.0.20        client" >> /etc/hosts
      echo "***> sudo apt-get install -y apache2"; sudo apt-get install -y apache2
    SHELL
    # Entrar y correr el comando sh de
  end

  config.vm.define "mysql" do |mysql|
    mysql.vm.box = "ubuntu/bionic64"
    mysql.vm.network "private_network", ip: "192.168.30.30"
    mysql.vm.network "forwarded_port", guest: 3030, host: 3030
    mysql.vm.provision "shell", inline: <<-SHELL
      echo "mysql" > /etc/hostname
      hostname -b mysql
      echo "192.168.30.10          apache" >> /etc/hosts
      echo "***> sudo apt-get install -y mysql-server"; sudo apt-get install -y mysql-server
    SHELL
    # Entrar y correr el comando sh de
  end

  config.vm.define "gateway" do |gateway|
    gateway.vm.box = "ubuntu/bionic64"
    gateway.vm.network "private_network", ip: "192.168.30.20"
    gateway.vm.network "forwarded_port", guest: 3000, host: 3000
    gateway.vm.provision "shell", inline: <<-SHELL
      echo "gatewayserver" > /etc/hostname
      hostname -b gatewayserver
      echo "192.168.30.10          webserver" >> /etc/hosts
      echo "192.168.30.30          mysql" >> /etc/hosts
    SHELL
    # Entrar y correr el comando sh de
  end
end