Vagrant.configure("2") do |config|

  config.vm.define "app" do |app|
    app.vm.box = "ubuntu/bionic64"
    app.vm.network "private_network", ip: "192.168.0.10"
    app.vm.network "public_network", ip: "192.168.0.11"
    app.vm.network "forwarded_port", guest: 3000, host: 3000
    app.vm.provision "shell", inline: <<-SHELL
        echo "app" > /etc/hostname
        hostname -b app
        echo "192.168.0.20        client" >> /etc/hosts
        echo "***sudo apt-get update***"; sudo apt-get update
        echo "***> sudo apt-get install -y nodejs"; sudo apt-get install -y nodejs
        echo "***> sudo apt-get install -y npm"; sudo apt-get install -y npm
        # echo "***> node app.js"; node app.js &
      SHELL
    end

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.vm.network "private_network", ip: "192.168.0.20"
    web.vm.network "public_network", ip: "192.168.0.21"
    #web.vm.network "forwarded_port", guest: 80, host: 80
    web.vm.provision "shell", inline: <<-SHELL
        echo "web" > /etc/hostname
        hostname -b web
        echo "192.168.0.10        app" >> /etc/hosts
        echo "***sudo apt-get update***"; sudo apt-get update
        echo "***sudo apt-get install -y apache2"; sudo apt-get install -y apache2
      SHELL
    end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/bionic64"
    db.vm.network "private_network", ip: "192.168.0.30"
    db.vm.network "public_network", ip: "192.168.0.31"
    db.vm.network "forwarded_port", guest: 3030, host: 3030
    db.vm.provision "shell", inline: <<-SHELL
        echo "db" > /etc/hostname
        hostname -b db
        echo "192.168.0.10        app" >> /etc/hosts
        echo "192.168.0.20        client" >> /etc/hosts
        echo "***sudo apt-get update***"; sudo apt-get update
        echo "***sudo apt-get install postgresql postgresql-contrib***"; sudo apt-get install -y postgresql postgresql-contrib
      SHELL
    end
end

# sudo iptables -A INPUT
#               -i enp0s8
#               -j ACCEPT
# sudo iptables -A OUTPUT
#               -o enp0s8
#               -i ACCEPT

#--------------------------------
# sudo iptables -P INPUT ACCEPT
#                  OUTPUT
# sudo iptables -F
